### ISSUE TITLE
Add to Chrome Web Store?

### ISSUE THREAD

**Issue by novacrazy** [BurakDev/3030protector#1]
Although it can be installed manually, Chrome permanently disables the extension whenever it restarts.

**Comment by BurakDev** [comment]
Already in my to-do list ;)

https://i.gyazo.com/e79115ca7cc80425b803a9f3130542c9.png

**Comment by novacrazy** [comment]
Also there is a typo in the link in the readme (chek should be check). Thought I'd tell you. 

Another suggestion would be to wrap the script in an immediately executed closure. I'm not sure if extension scripts are executed in the same scope as website scripts, but it never hurts to be safe.
